spring:
  
  application:
    name: integrations-service-broker
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${spring.application.name}
      authentication-database: admin
      username: admin
      password: admin

keycloak:
  server-url: localhost
  realm: master
  client-id: admin
  client-secret: admin
  username: admin
  password: admin
